"""Public Python API for interp-lab."""

__version__ = "3.1.0"

from interp_lab.schema import (
    CandidateMatch,
    Criterion,
    FeatureCard,
    FeatureEvidence,
    FeatureFingerprint,
    InspectionReport,
    MatchReport,
)
from interp_lab.hf_records import PromptDatasetSplitSummary, PromptDatasetSummary
from interp_lab.criterion_lab import (
    CriterionAssayValidationResult,
    CriterionLabPresetInfo,
    CriterionLabWriteResult,
)
from interp_lab.workflows import RunTemplateWriteResult
from interp_lab.contracts import public_api_contract
from interp_lab.reporting import load_inspection_report, load_match_report

# DOSSIER_SCHEMA and write_dossier_markdown are importable conveniences; the
# stable contract surface (__all__ / contracts.PUBLIC_API_EXPORTS) carries the
# load/update/summary callables.
from interp_lab.dossier import DOSSIER_SCHEMA, load_dossier, write_dossier_markdown

from interp_lab.api import (
    FeatureInterventionResult,
    PathPatchResult,
    HfSaePathValidation,
    SaeTrainingResult,
    WrittenGraph,
    WrittenGraphSummary,
    WrittenGraphValidation,
    WrittenInspection,
    WrittenMatch,
    WrittenMatchValidation,
    WrittenAnalysis,
    apply_steering,
    attribution_graph,
    attribution_graph_summary,
    build_prompts,
    calibrate,
    capabilities,
    check_explanation_consistency,
    compare,
    compare_model_families,
    compare_runs,
    compile_criterion,
    criterion_lab,
    criterion_lab_presets,
    demo_sweep,
    doctor,
    dossier_summary,
    export_steering_vector,
    inspect,
    intervene,
    load_steering_artifact,
    match_text_pivot,
    migrate_inspection_report,
    path_patch,
    plan_evidence,
    prepare_sae_prompts,
    publish_hf_artifact,
    profile_environment,
    quant_diff,
    release_check,
    run,
    scale_plan,
    scaffold_run,
    score_prompts,
    search_features,
    train_sae,
    update_dossier,
    validate_attribution_graph,
    validate_criterion_assay,
    validate_hf_sae_paths,
    validate_matches,
)

__all__ = [
    "CandidateMatch",
    "CriterionAssayValidationResult",
    "CriterionLabPresetInfo",
    "CriterionLabWriteResult",
    "Criterion",
    "FeatureCard",
    "FeatureEvidence",
    "FeatureFingerprint",
    "FeatureInterventionResult",
    "InspectionReport",
    "MatchReport",
    "PathPatchResult",
    "HfSaePathValidation",
    "PromptDatasetSplitSummary",
    "PromptDatasetSummary",
    "RunTemplateWriteResult",
    "SaeTrainingResult",
    "WrittenGraph",
    "WrittenGraphSummary",
    "WrittenGraphValidation",
    "WrittenInspection",
    "WrittenMatch",
    "WrittenMatchValidation",
    "WrittenAnalysis",
    "apply_steering",
    "attribution_graph",
    "attribution_graph_summary",
    "build_prompts",
    "calibrate",
    "capabilities",
    "check_explanation_consistency",
    "compare",
    "compare_model_families",
    "compare_runs",
    "compile_criterion",
    "criterion_lab",
    "criterion_lab_presets",
    "demo_sweep",
    "doctor",
    "dossier_summary",
    "export_steering_vector",
    "inspect",
    "intervene",
    "load_dossier",
    "load_inspection_report",
    "load_match_report",
    "load_steering_artifact",
    "match_text_pivot",
    "migrate_inspection_report",
    "path_patch",
    "plan_evidence",
    "prepare_sae_prompts",
    "public_api_contract",
    "publish_hf_artifact",
    "profile_environment",
    "quant_diff",
    "release_check",
    "run",
    "scale_plan",
    "scaffold_run",
    "score_prompts",
    "search_features",
    "train_sae",
    "update_dossier",
    "validate_attribution_graph",
    "validate_criterion_assay",
    "validate_hf_sae_paths",
    "validate_matches",
]
