"""Public Python API for interp-lab."""

from oracle_sae.schema import (
    CandidateMatch,
    Criterion,
    FeatureCard,
    FeatureEvidence,
    FeatureFingerprint,
    InspectionReport,
    MatchReport,
)
from oracle_sae.hf_records import PromptDatasetSplitSummary, PromptDatasetSummary
from oracle_sae.criterion_lab import (
    CriterionAssayValidationResult,
    CriterionLabPresetInfo,
    CriterionLabWriteResult,
)
from oracle_sae.workflows import RunTemplateWriteResult
from interp_lab.contracts import public_api_contract

from interp_lab.api import (
    FeatureInterventionResult,
    PathPatchResult,
    HfSaePathValidation,
    SaeTrainingResult,
    WrittenGraph,
    WrittenGraphSummary,
    WrittenGraphValidation,
    WrittenInspection,
    WrittenMatch,
    WrittenMatchValidation,
    WrittenAnalysis,
    attribution_graph,
    attribution_graph_summary,
    build_prompts,
    check_explanation_consistency,
    compare,
    compare_model_families,
    criterion_lab,
    criterion_lab_presets,
    demo_sweep,
    doctor,
    inspect,
    intervene,
    match_text_pivot,
    path_patch,
    prepare_sae_prompts,
    publish_hf_artifact,
    profile_environment,
    release_check,
    run,
    scale_plan,
    scaffold_run,
    search_features,
    train_sae,
    validate_attribution_graph,
    validate_criterion_assay,
    validate_hf_sae_paths,
    validate_matches,
)

__all__ = [
    "CandidateMatch",
    "CriterionAssayValidationResult",
    "CriterionLabPresetInfo",
    "CriterionLabWriteResult",
    "Criterion",
    "FeatureCard",
    "FeatureEvidence",
    "FeatureFingerprint",
    "FeatureInterventionResult",
    "InspectionReport",
    "MatchReport",
    "PathPatchResult",
    "HfSaePathValidation",
    "PromptDatasetSplitSummary",
    "PromptDatasetSummary",
    "RunTemplateWriteResult",
    "SaeTrainingResult",
    "WrittenGraph",
    "WrittenGraphSummary",
    "WrittenGraphValidation",
    "WrittenInspection",
    "WrittenMatch",
    "WrittenMatchValidation",
    "WrittenAnalysis",
    "attribution_graph",
    "attribution_graph_summary",
    "build_prompts",
    "check_explanation_consistency",
    "compare",
    "compare_model_families",
    "criterion_lab",
    "criterion_lab_presets",
    "demo_sweep",
    "doctor",
    "inspect",
    "intervene",
    "match_text_pivot",
    "path_patch",
    "prepare_sae_prompts",
    "public_api_contract",
    "publish_hf_artifact",
    "profile_environment",
    "release_check",
    "run",
    "scale_plan",
    "scaffold_run",
    "search_features",
    "train_sae",
    "validate_attribution_graph",
    "validate_criterion_assay",
    "validate_hf_sae_paths",
    "validate_matches",
]

__version__ = "1.0.0"
