"""Machine-readable public API and schema contracts."""

from __future__ import annotations

from copy import deepcopy
from typing import Any

from interp_lab import __version__
from interp_lab.criterion_lab import PRESET_SCHEMA_VERSION
from interp_lab.demo_sweep import REAL_MODEL_DEMO_SWEEP_SCHEMA
from interp_lab.env_profile import SCHEMA_VERSION as ENV_PROFILE_SCHEMA
from interp_lab.explanation_reports import (
    EXPLANATION_CONSISTENCY_SCHEMA,
    FEATURE_SEARCH_SCHEMA,
    MODEL_FAMILY_COMPARISON_SCHEMA,
    TEXT_PIVOT_MATCH_SCHEMA,
)
from interp_lab.feature_interventions import INTERVENTION_SCHEMA, PLAN_SCHEMA
from interp_lab.release_check import REAL_MODEL_DEMO_SCHEMA, RELEASE_CHECK_SCHEMA
from interp_lab.schema import INSPECTION_REPORT_SCHEMA, MATCH_REPORT_SCHEMA
from interp_lab.web_server import STUDIO_HISTORY_SCHEMA

PUBLIC_API_CONTRACT_SCHEMA = "interp-lab.public_api_contract.v1"

PUBLIC_API_EXPORTS = [
    "CandidateMatch",
    "CriterionAssayValidationResult",
    "CriterionLabPresetInfo",
    "CriterionLabWriteResult",
    "Criterion",
    "FeatureCard",
    "FeatureEvidence",
    "FeatureFingerprint",
    "FeatureInterventionResult",
    "InspectionReport",
    "MatchReport",
    "PathPatchResult",
    "HfSaePathValidation",
    "PromptDatasetSplitSummary",
    "PromptDatasetSummary",
    "RunTemplateWriteResult",
    "SaeTrainingResult",
    "WrittenGraph",
    "WrittenGraphSummary",
    "WrittenGraphValidation",
    "WrittenInspection",
    "WrittenMatch",
    "WrittenMatchValidation",
    "WrittenAnalysis",
    "attribution_graph",
    "attribution_graph_summary",
    "build_prompts",
    "check_explanation_consistency",
    "compare",
    "compare_model_families",
    "criterion_lab",
    "criterion_lab_presets",
    "demo_sweep",
    "doctor",
    "inspect",
    "intervene",
    "match_text_pivot",
    "path_patch",
    "prepare_sae_prompts",
    "public_api_contract",
    "publish_hf_artifact",
    "profile_environment",
    "release_check",
    "run",
    "scale_plan",
    "scaffold_run",
    "search_features",
    "train_sae",
    "validate_attribution_graph",
    "validate_criterion_assay",
    "validate_hf_sae_paths",
    "validate_matches",
]

SCHEMA_CONTRACTS = {
    "attribution_graph": "interp-lab.attribution_graph.v1",
    "attribution_graph_summary": "interp-lab.attribution_graph_summary.v1",
    "criterion_assay_validation": "interp-lab.criterion_assay_validation.v1",
    "criterion_lab": "interp-lab.criterion_lab.v1",
    "criterion_lab_preset": PRESET_SCHEMA_VERSION,
    "environment_profile": ENV_PROFILE_SCHEMA,
    "explanation_consistency": EXPLANATION_CONSISTENCY_SCHEMA,
    "feature_search": FEATURE_SEARCH_SCHEMA,
    "graph_validation": "interp-lab.graph_validation.v1",
    "inspection_report": INSPECTION_REPORT_SCHEMA,
    "intervention_plan": PLAN_SCHEMA,
    "intervention_record": "interp-lab.intervention_record.v1",
    "intervention_result": INTERVENTION_SCHEMA,
    "match_report": MATCH_REPORT_SCHEMA,
    "match_validation": "interp-lab.match_validation.v1",
    "model_family_comparison": MODEL_FAMILY_COMPARISON_SCHEMA,
    "path_patch": "interp-lab.path_patch.v1",
    "public_api_contract": PUBLIC_API_CONTRACT_SCHEMA,
    "real_model_demo": REAL_MODEL_DEMO_SCHEMA,
    "real_model_demo_sweep": REAL_MODEL_DEMO_SWEEP_SCHEMA,
    "release_check": RELEASE_CHECK_SCHEMA,
    "run_manifest": "interp-lab.run.v1",
    "sae": "interp-lab.sae.v1",
    "sae_prompt_pack": "interp-lab.sae_prompt_pack.v1",
    "scale_plan": "interp-lab.scale_plan.v2",
    "studio_history": STUDIO_HISTORY_SCHEMA,
    "text_pivot_match": TEXT_PIVOT_MATCH_SCHEMA,
}

PUBLIC_API_SIGNATURES = {
    "attribution_graph": ["report", "out", "markdown_out", "html_out", "path_records"],
    "attribution_graph_summary": ["graph", "out"],
    "build_prompts": ["out", "positive", "negative", "positive_prompt", "negative_prompt"],
    "check_explanation_consistency": ["reports", "out", "markdown_out", "html_out", "min_similarity", "max_rank_span", "top_k"],
    "compare": ["left", "right", "out", "top_k"],
    "compare_model_families": ["members", "out", "markdown_out", "html_out", "top_k", "min_score"],
    "criterion_lab": ["out", "model", "preset", "preset_file", "criterion", "workflow", "run_dir"],
    "demo_sweep": ["repo_root", "manifest_dir", "demos", "out", "run", "allow_external"],
    "inspect": [
        "model",
        "criterion",
        "backend",
        "features",
        "records",
        "interventions",
        "out",
        "html_out",
        "top_k",
        "require_interventions",
        "allow_intervention_criterion_mismatch",
        "neuronpedia_feature",
        "neuronpedia_features",
        "neuronpedia_base_url",
        "saelens_release",
        "saelens_sae_id",
        "saelens_feature_indexes",
        "saelens_max_features",
        "saelens_device",
        "saelens_force_download",
        "saelens_feature_metadata",
        "goodfire_top_k",
        "goodfire_api_key_env",
        "scope_source",
        "scope_release",
        "scope_sae_id",
        "scope_feature_indexes",
        "scope_max_features",
        "scope_device",
        "scope_force_download",
        "scope_feature_metadata",
        "verbalizer",
        "nla_explanations",
        "nla_min_confidence",
        "nla_fallback",
    ],
    "intervene": [
        "model",
        "dataset",
        "criterion",
        "out",
        "features",
        "report",
        "records",
        "top_k",
        "sae",
        "mode",
        "strength_sweep",
        "ablate_value",
        "target_tokens",
        "device",
        "max_length",
        "plan_out",
        "dry_run",
        "model_class",
        "trust_remote_code",
        "local_files_only",
        "torch_dtype",
        "device_map",
        "model_kwargs",
        "tokenizer_kwargs",
    ],
    "match_text_pivot": ["left", "right", "out", "markdown_out", "html_out", "top_k", "per_left", "min_score", "min_text_score"],
    "path_patch": ["model", "dataset", "source_sae", "target_sae", "out", "criterion"],
    "prepare_sae_prompts": ["dataset", "out_dir", "train_ratio", "causal_ratio", "validation_ratio"],
    "publish_hf_artifact": ["repo_id", "paths", "repo_type", "private", "dry_run"],
    "release_check": ["repo_root"],
    "run": ["config", "dry_run"],
    "scale_plan": ["model_params", "tokens", "d_model", "selected_layers", "latent_dim", "profile"],
    "scaffold_run": ["out", "workflow", "model", "criterion", "run_dir"],
    "search_features": ["query", "reports", "out", "markdown_out", "html_out", "top_k", "min_score"],
    "train_sae": [
        "out",
        "records",
        "model",
        "hf_model",
        "dataset",
        "records_out",
        "preset",
        "layer",
        "pool",
        "token_mode",
        "latent_dim",
        "expansion_factor",
        "method",
        "epochs",
        "batch_size",
        "lr",
        "l1",
        "sparsity",
        "top_k",
        "jump_threshold",
        "validation_fraction",
        "dead_latent_threshold",
        "seed",
        "device",
        "max_length",
        "max_records",
        "top_k_features",
        "decoder_signature_size",
        "causal_out",
        "criterion",
        "causal_top_k",
        "causal_strength_sweep",
        "target_tokens",
        "model_class",
        "trust_remote_code",
        "local_files_only",
        "torch_dtype",
        "device_map",
        "model_kwargs",
        "tokenizer_kwargs",
    ],
    "validate_attribution_graph": ["graph", "path_records", "out", "graph_out", "require_controls"],
    "validate_criterion_assay": ["preset", "preset_file", "preset_dir", "out"],
    "validate_hf_sae_paths": ["graph", "model", "dataset", "source_sae", "target_sae", "out"],
    "validate_matches": ["matches", "out", "html_out", "top_k"],
}


def public_api_contract() -> dict[str, Any]:
    """Return the stable public API and schema contract for agents and tests."""
    return {
        "schema_version": PUBLIC_API_CONTRACT_SCHEMA,
        "package": "interp-lab",
        "package_version": __version__,
        "exports": list(PUBLIC_API_EXPORTS),
        "schemas": deepcopy(SCHEMA_CONTRACTS),
        "signatures": deepcopy(PUBLIC_API_SIGNATURES),
    }
